- to prevent other images on interfering with the click on canvas, make sure it's pointer event is set to none "pointer-events: none;" mouse controls -the ES6 function automatics inherits the "this." keyword from the parent scope
error: 'mousemove'